name: Run the tests please

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  do_the_build_please:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install python3.8
      run: sudo apt install -y python3.8

    - name: Run tests
      run: python3 omegastar_test.py